# Generated by Django 5.1 on 2024-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareStorageCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.URLField()),
                ('access_key_id', models.CharField(max_length=100)),
                ('secret_access_key', models.CharField(max_length=100)),
            ],
        ),
    ]
