# Generated by Django 5.1 on 2024-08-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_cloudflarestoragecredential'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloudflareStorageCredential',
            new_name='CloudflareCredential',
        ),
    ]
