# Generated by Django 5.1 on 2024-08-24 12:27

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_cloudflarestoragecredential_cloudflarecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudflarecredential',
            name='bucket',
            field=models.CharField(default=builtins.print, max_length=100),
            preserve_default=False,
        ),
    ]
