# Generated by Django 5.1 on 2024-08-25 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_cloudflarecredential_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.URLField()),
                ('access_key_id', models.CharField(max_length=100)),
                ('secret_access_key', models.CharField(max_length=100)),
                ('bucket', models.CharField(max_length=100)),
                ('access_url', models.URLField(max_length=100)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='CloudflareCredential',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
